[router]
10.0.15.61 ansible_host=10.0.15.61
10.0.15.62 ansible_host=10.0.15.62
10.0.15.63 ansible_host=10.0.15.63
10.0.15.64 ansible_host=10.0.15.64
10.0.15.65 ansible_host=10.0.15.65

[router:vars]
ansible_user=admin
ansible_password=cisco
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostkeyAlgorithms=+ssh-rsa'