[router]
CSR1kv ansible_host=10.0.15.62

[router:vars]
ansible_user=admin
ansible_password=cisco
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostkeyAlgorithms=+ssh-rsa'