---
- name: Show running configuration
  hosts: router
  gather_facts: false
  connection: network_cli

  vars:
    # ตั้งค่า default (เผื่อไว้) แต่จะถูก override โดย -e
    output_filename: "./show_run_{{ STUDENT_ID }}_{{ inventory_hostname }}.txt"

  tasks:
    - name: Show running-config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: showrun

    - name: Save showrun to file
      copy:
        content: "{{ showrun.stdout[0] }}"
        dest: "{{ output_filename }}"
      delegate_to: localhost